### ISSUE TITLE
Always says incorrect ASIN or results in Server 500 error

### ISSUE THREAD

**Issue by letsstartbeinganon** [djdembeck/bragibooks#100]
I am correctly using the Audible.com ASINs but Bragi always comes back and says either 'incorrect ASIN' or it ends up crashing and giving me a Server 500 error.  Any idea on how this can be fixed?

**Comment by whoiskevinrich** [comment]
Same issue here. Running in Docker

**Comment by djdembeck** [comment]
What asins do you see this error on?

**Comment by whoiskevinrich** [comment]
One Example: B005HG7BWC

**Comment by Hoempi** [comment]
Another example: B00TLZ3J3K

**Comment by djdembeck** [comment]
> One Example: B005HG7BWC
There is no data on this ASIN from audible:
https://api.audible.com/1.0/catalog/products/B005HG7BWC?response_groups=category_ladders,contributors,product_desc,product_extended_attrs,product_attrs,media,rating,series
```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Required key 'authors' does not exist in Audible API response for ASIN B005HG7BWC"
}
```

> Another example: B00TLZ3J3K

This ASIN seems ok to me.

**Comment by letsstartbeinganon** [comment]
I have tried the following:

B09VHWHJS2
B09VHZCQB1
B08JCM5KHZ
B08JCPF9HM
B09FBSHXBQ
0525633723

The last one I'm not sure is a valid ASIN but it's what Audible.com lists in the bit where the ASINs usually are for Obama's _A Promised Land_.

**Comment by djdembeck** [comment]
May I ask where you are getting some of these? 3 of them are valid (including the last one). The others have no data from Audible, so I'm not sure where you got them? Such as `https://www.audible.com/pd/B09VHZCQB1`

**Comment by letsstartbeinganon** [comment]
It’s possible I got some from Amazon or Audible UK which explains why some don’t work but the fact that three are valid yet still return Bad ASIN or Server Error 500 messages is obviously the main concern here.

**Comment by letsstartbeinganon** [comment]
Also get Bad ASIN on B00JQN221C

Which then led to Bragibooks crashing

**Comment by whoiskevinrich** [comment]
Ready Player One: B005HG7BWC

Comes from Amazon's Audiobook option here: 
https://www.amazon.com/Ready-Player-One-Ernest-Cline-audiobook/dp/B005HG7BWC

![image](https://user-images.githubusercontent.com/2496620/189543140-4dbd3bce-3d4e-40fc-9aea-bb3ff6efcc59.png)

**Comment by Hoempi** [comment]
> > Another example: B00TLZ3J3K
> 
> This ASIN seems ok to me.

That's great, but still crashes for me. I now tried 3844920684 by using Audible.com and taking the ASIN from the URL:

![grafik](https://user-images.githubusercontent.com/40570297/189548336-e8e3596b-615a-4429-a37e-ea2b13f6abbd.png)

It downloads the cover and then crashes with server error 500 again. I restarted the Docker container beforehand and this is what the log output is:
`[2022-09-11 20:47:35 +0000] [13] [INFO] Starting gunicorn 20.1.0

[2022-09-11 20:47:35 +0000] [13] [INFO] Listening at: http://0.0.0.0:8000 (13)

[2022-09-11 20:47:35 +0000] [13] [INFO] Using worker: gthread

[2022-09-11 20:47:35 +0000] [14] [INFO] Booting worker with pid: 14

[2022-09-11 20:47:35 +0000] [15] [INFO] Booting worker with pid: 15

Internal Server Error: /import/match

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view

    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch

    return handler(request, *args, **kwargs)

  File "/home/app/web/importer/views.py", line 138, in post

    merge_object.run_m4b_merge()

  File "/home/app/web/utils/merge.py", line 50, in run_m4b_merge

    self.m4b.run_merge()

  File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 254, in run_merge

    self.merge_multiple_files()

  File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 275, in merge_multiple_files

    target_bitrate = self.find_bitrate(first_file)

  File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 228, in find_bitrate

    int(mediainfo(file_input)['bit_rate']) / 1000

`

**Comment by djdembeck** [comment]
> It’s possible I got some from Amazon or Audible UK which explains why some don’t work but the fact that three are valid yet still return Bad ASIN or Server Error 500 messages is obviously the main concern here.

If you can get your logs that would help explain what caused the issue.



> Ready Player One: B005HG7BWC
> 
> Comes from Amazon's Audiobook option here: https://www.amazon.com/Ready-Player-One-Ernest-Cline-audiobook/dp/B005HG7BWC
> 
> ![image](https://user-images.githubusercontent.com/2496620/189543140-4dbd3bce-3d4e-40fc-9aea-bb3ff6efcc59.png)

You need the actual ASIN from Audible.com itself. Amazon lists different ASINs on their product page.



> > > Another example: B00TLZ3J3K
> > 
> > 
> > This ASIN seems ok to me.
> 
> That's great, but still crashes for me. I now tried 3844920684 by using Audible.com and taking the ASIN from the URL:
> 
> ![grafik](https://user-images.githubusercontent.com/40570297/189548336-e8e3596b-615a-4429-a37e-ea2b13f6abbd.png)
> 
> It downloads the cover and then crashes with server error 500 again. I restarted the Docker container beforehand and this is what the log output is:
> 
> > [2022-09-11 20:47:35 +0000] [13] [INFO] Starting gunicorn 20.1.0
> > [2022-09-11 20:47:35 +0000] [13] [INFO] Listening at: http://0.0.0.0:8000 (13)
> > [2022-09-11 20:47:35 +0000] [13] [INFO] Using worker: gthread
> > [2022-09-11 20:47:35 +0000] [14] [INFO] Booting worker with pid: 14
> > [2022-09-11 20:47:35 +0000] [15] [INFO] Booting worker with pid: 15
> > Internal Server Error: /import/match
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
> > response = get_response(request)
> > File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
> > response = wrapped_callback(request, *callback_args, **callback_kwargs)
> > File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
> > return self.dispatch(request, *args, **kwargs)
> > File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
> > return handler(request, *args, **kwargs)
> > File "/home/app/web/importer/views.py", line 138, in post
> > merge_object.run_m4b_merge()
> > File "/home/app/web/utils/merge.py", line 50, in run_m4b_merge
> > self.m4b.run_merge()
> > File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 254, in run_merge
> > self.merge_multiple_files()
> > File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 275, in merge_multiple_files
> > target_bitrate = self.find_bitrate(first_file)
> > File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 228, in find_bitrate
> > int(mediainfo(file_input)['bit_rate']) / 1000

Is this the end of the log? It looks like it's cut off at the bottom.

**Comment by Hoempi** [comment]
@djdembeck 

Sorry, obviously I did not mark everything when copying. This time it should be complete:

> Starting with UID: 1027, GID: 1000
> Operations to perform:
>   Apply all migrations: auth, contenttypes, importer, sessions
> Running migrations:
>   No migrations to apply.
> [2022-09-12 00:35:28 +0000] [25] [INFO] Starting gunicorn 20.1.0
> [2022-09-12 00:35:28 +0000] [25] [INFO] Listening at: http://0.0.0.0:8000 (25)
> [2022-09-12 00:35:28 +0000] [25] [INFO] Using worker: gthread
> [2022-09-12 00:35:28 +0000] [26] [INFO] Booting worker with pid: 26
> [2022-09-12 00:35:28 +0000] [27] [INFO] Booting worker with pid: 27
> Internal Server Error: /import/match
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/home/app/web/importer/views.py", line 138, in post
>     merge_object.run_m4b_merge()
>   File "/home/app/web/utils/merge.py", line 50, in run_m4b_merge
>     self.m4b.run_merge()
>   File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 254, in run_merge
>     self.merge_multiple_files()
>   File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 275, in merge_multiple_files
>     target_bitrate = self.find_bitrate(first_file)
>   File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 228, in find_bitrate
>     int(mediainfo(file_input)['bit_rate']) / 1000
> KeyError: 'bit_rate'
> Not Found: /favicon.ico

My guess is the 'bit_rate' key, but I did not look into that Python file to verify this, as that's not my kind of expertise.

**Comment by letsstartbeinganon** [comment]
> If you can get your logs that would help explain what caused the issue.

The logs from Docker?  Weirdly after it crashed it seems to have wiped the logs but I will see what I can find and post here in due course.

**Comment by djdembeck** [comment]
@Hoempi interesting. What does
`mediainfo your_file.EXT` return? The error is caused by the source file not having bit rate info for the audio, which is quite odd.

**Comment by Hoempi** [comment]
> @Hoempi interesting. What does
> 
> ```
> mediainfo your_file.EXT
> ```
> 
> return? The error is caused by the source file not having bit rate info for the audio, which is quite odd.
> 
> I should be able to improve the fault here, and let the program auto determine a bitrate to use, which won't be optimal but won't crash.

Will gladly do so, but where to find that command? I started the terminal in the container, but the command was not recognized. I also did not find it in the subdirs I took a look into.

On a side note, these are both books which came as MP3 CDs. I will try later with something I ripped myself with fre:ac.

**Comment by letsstartbeinganon** [comment]
This is what my Docker logs say but they did in fact clear at some point after it crashed

2022-09-11T13:36:17.868544935Z	stdout	[2022-09-11 13:36:17 +0000] [26] [INFO] Handling signal: winch
2022-09-11T13:35:34.308469453Z	stdout	[2022-09-11 13:35:34 +0000] [28] [INFO] Booting worker with pid: 28
2022-09-11T13:35:34.279623474Z	stdout	[2022-09-11 13:35:34 +0000] [27] [INFO] Booting worker with pid: 27
2022-09-11T13:35:34.274970990Z	stdout	[2022-09-11 13:35:34 +0000] [26] [INFO] Using worker: gthread
2022-09-11T13:35:34.274892947Z	stdout	[2022-09-11 13:35:34 +0000] [26] [INFO] Listening at: http://0.0.0.0:8000 (26)
2022-09-11T13:35:34.274506559Z	stdout	[2022-09-11 13:35:34 +0000] [26] [INFO] Starting gunicorn 20.1.0
2022-09-11T13:35:33.289634757Z	stdout	  No migrations to apply.
2022-09-11T13:35:32.970640660Z	stdout	[36;1mRunning migrations:[0m
2022-09-11T13:35:32.952811821Z	stdout	[1m  Apply all migrations: [0mauth, contenttypes, importer, sessions
2022-09-11T13:35:32.952345065Z	stdout	[36;1mOperations to perform:[0m
2022-09-11T13:35:27.495658478Z	stdout	Starting with UID: 99, GID: 100

**Comment by djdembeck** [comment]
Please everyone try the new `main` or `develop` images. This includes a new version of `m4b-merge`

**Comment by Hoempi** [comment]
Good morning @djdembeck,

thanks a lot, that seems to have fixed the bug with the bit_rate. I got to the confirmation page. But from there it returned to the import page:

> 
> Starting with UID: 1027, GID: 1000
> Operations to perform:
>   Apply all migrations: auth, contenttypes, importer, sessions
> Running migrations:
>   No migrations to apply.
> [2022-09-15 00:36:31 +0000] [24] [INFO] Starting gunicorn 20.1.0
> [2022-09-15 00:36:31 +0000] [24] [INFO] Listening at: http://0.0.0.0:8000 (24)
> [2022-09-15 00:36:31 +0000] [24] [INFO] Using worker: gthread
> [2022-09-15 00:36:31 +0000] [25] [INFO] Booting worker with pid: 25
> [2022-09-15 00:36:31 +0000] [26] [INFO] Booting worker with pid: 26
> Unable to determine bitrate, using default
> Unable to determine samplerate, using default
> an error occured, that has not been caught:
> Array
> (
>     [type] => 4
>     [message] => syntax error, unexpected '|', expecting variable (T_VARIABLE)
>     [file] => phar:///usr/local/bin/m4b-tool/vendor/psr/cache/src/CacheItemInterface.php
>     [line] => 104
> )
> PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in phar:///usr/local/bin/m4b-tool/vendor/psr/cache/src/CacheItemInterface.php on line 104
> ERROR: unable to open for write: /output/Simon Beckett/David Hunter/Die Chemie des Todes/Die Chemie des Todes - David Hunter 1.m4b
> No session data found, returning to import page

But the container has a UID/GID pair with write privileges and was able to create the folder structure as well as the chapter textfile:
![grafik](https://user-images.githubusercontent.com/40570297/190318399-dd203057-c04f-45f7-9a7e-ee69cae0b277.png)

**Comment by letsstartbeinganon** [comment]
I'm afraid I'm still getting Bad ASIN errors on several ASINs like 0241991420 and B00VXXUFYO...

**Comment by djdembeck** [comment]
> unexpected '|', expecting variable (T_VARIABLE)

Fixed in the latest docker version, it was an m4b-tool issue.

> I'm afraid I'm still getting Bad ASIN errors on several ASINs like 0241991420 and B00VXXUFYO...

`0241991420` works fine for me in bragibooks. There is likely an error with your setup. I would need logs showing the error to know what your issue actually is.

**Comment by Hoempi** [comment]
> > unexpected '|', expecting variable (T_VARIABLE)
> 
> Fixed in the latest docker version, it was an m4b-tool issue.
Great, thanks a lot. I’ll be looking out for a Watchtower notification.

**Comment by Hoempi** [comment]
Watchtower updated and I could succesfully create a first .m4b. Playing and fast forwarding to the end shows it seems to be complete.

However, after entering the ASIN I never got to the confirmation page, it just started right away. I guess this is not intended? Should I open a new bug issue, to not mix topics?

**Comment by letsstartbeinganon** [comment]
I'm afraid there isn't anything in my log - it keeps getting wiped?  Here's it's most recent entry:

<html>
<body>


date | stream | content
-- | -- | --
2022-09-26T13:35:40.772318484Z | stdout | [2022-09-26 13:35:40 +0000] [16] [INFO] Booting worker with pid: 16
2022-09-26T13:35:40.680884485Z | stdout | [2022-09-26 13:35:40 +0000] [15] [INFO] Booting worker with pid: 15
2022-09-26T13:35:40.675274155Z | stdout | [2022-09-26 13:35:40 +0000] [8] [INFO] Using worker: gthread
2022-09-26T13:35:40.675123994Z | stdout | [2022-09-26 13:35:40 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
2022-09-26T13:35:40.674488028Z | stdout | [2022-09-26 13:35:40 +0000] [8] [INFO] Starting gunicorn 20.1.0
2022-09-26T13:35:39.205215374Z | stdout | No migrations to apply.
2022-09-26T13:35:39.205085971Z | stdout | [36;1mRunning migrations:[0m
2022-09-26T13:35:39.192259183Z | stdout | [1m  Apply all migrations: [0mauth, contenttypes, importer, sessions
2022-09-26T13:35:39.191836546Z | stdout | [36;1mOperations to perform:[0m
2022-09-26T13:35:32.311309692Z | stdout | Starting with UID: 99, GID: 100


</body>
</html>

**Comment by djdembeck** [comment]
@letsstartbeinganon 

These are just the startup logs, which offer no information on what went wrong. If your system is clearing the logs on docker restart, you can try following the logs manually with `docker logs bragibooks --follow` and then run the problem file.

**Comment by letsstartbeinganon** [comment]
> @letsstartbeinganon
> 
> These are just the startup logs, which offer no information on what went wrong. If your system is clearing the logs on docker restart, you can try following the logs manually with `docker logs bragibooks --follow` and then run the problem file.

Sorry for the long delay in reply.  I'm still getting the error even when using your tool to search for a book by name - ie with an ASIN Bragibooks has found.  Are these the logs you're after?

date	stream	content
2023-06-25T21:30:39.131377856Z	stdout	No results found for query Stormlight Archives 1 pw spit
2023-06-25T21:30:24.902462776Z	stdout	No results found for query Stormlight Archives 1 pw spit
2023-06-25T21:30:15.021647473Z	stdout	No results found for query Stormlight Archives 1 pw spit
2023-06-25T21:29:37.804832235Z	stdout	No results found for query Brandon Sanderson The Way of Kings 7176
2023-06-25T21:29:37.493797593Z	stdout	No results found for query Brandon Sanderson The Way of Kings 7676
2023-06-25T21:29:37.477407816Z	stdout	No results found for query Brandon Sanderson The Way of Kings 7576
2023-06-25T21:29:37.473531880Z	stdout	No results found for query Brandon Sanderson The Way of Kings 7376
2023-06-25T21:29:37.382312988Z	stdout	No results found for query Brandon Sanderson The Way of Kings 7476
2023-06-25T21:29:37.330156799Z	stdout	No results found for query Brandon Sanderson The Way of Kings 7276
2023-06-25T21:29:37.223637913Z	stdout	No results found for query Brandon Sanderson The Way of Kings 7076
2023-06-25T21:29:36.933550817Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6976
2023-06-25T21:29:36.925615233Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6776
2023-06-25T21:29:36.920000853Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6876
2023-06-25T21:29:36.883555538Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6376
2023-06-25T21:29:36.775327283Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6576
2023-06-25T21:29:36.584914563Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6676
2023-06-25T21:29:36.392309788Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6276
2023-06-25T21:29:36.365880669Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6476
2023-06-25T21:29:36.361859546Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6176
2023-06-25T21:29:36.277429163Z	stdout	No results found for query Brandon Sanderson The Way of Kings 6076
2023-06-25T21:29:36.182795769Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5976
2023-06-25T21:29:36.161193137Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5776
2023-06-25T21:29:35.915461262Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5876
2023-06-25T21:29:35.834367237Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5276
2023-06-25T21:29:35.797681765Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5676
2023-06-25T21:29:35.715700363Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5076
2023-06-25T21:29:35.548256863Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5476
2023-06-25T21:29:35.536897754Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5376
2023-06-25T21:29:35.530048033Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5576
2023-06-25T21:29:35.136390708Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4476
2023-06-25T21:29:35.094182431Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4976
2023-06-25T21:29:35.053504348Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4776
2023-06-25T21:29:35.052681714Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4876
2023-06-25T21:29:35.047803781Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4676
2023-06-25T21:29:35.028020359Z	stdout	No results found for query Brandon Sanderson The Way of Kings 5176
2023-06-25T21:29:34.494759421Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4276
2023-06-25T21:29:34.460019716Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4076
2023-06-25T21:29:34.331740624Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4576
2023-06-25T21:29:34.311200922Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4376
2023-06-25T21:29:34.161233031Z	stdout	No results found for query Brandon Sanderson The Way of Kings 4176
2023-06-25T21:29:34.134337488Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3876
2023-06-25T21:29:33.921593880Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3676
2023-06-25T21:29:33.896066150Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3476
2023-06-25T21:29:33.775000840Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3976
2023-06-25T21:29:33.758987878Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3776
2023-06-25T21:29:33.661227825Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3576
2023-06-25T21:29:33.569741939Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3376
2023-06-25T21:29:33.481475446Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3176
2023-06-25T21:29:33.471781297Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3076
2023-06-25T21:29:33.311458415Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2876
2023-06-25T21:29:33.310321416Z	stdout	No results found for query Brandon Sanderson The Way of Kings 3276
2023-06-25T21:29:33.297475641Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2976
2023-06-25T21:29:32.968149871Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2776
2023-06-25T21:29:32.963625925Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2676
2023-06-25T21:29:32.883609119Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2276
2023-06-25T21:29:32.851916919Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2376
2023-06-25T21:29:32.677418340Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2476
2023-06-25T21:29:32.677265805Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2576
2023-06-25T21:29:32.404708125Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1776
2023-06-25T21:29:32.365835638Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1576
2023-06-25T21:29:32.362064050Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1976
2023-06-25T21:29:32.361559619Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2176
2023-06-25T21:29:32.358437984Z	stdout	No results found for query Brandon Sanderson The Way of Kings 2076
2023-06-25T21:29:32.289463465Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1876
2023-06-25T21:29:31.431501002Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1676
2023-06-25T21:29:31.400008004Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1376
2023-06-25T21:29:31.399837209Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1476
2023-06-25T21:29:31.341208933Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1276
2023-06-25T21:29:31.268464809Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1176
2023-06-25T21:29:31.149323951Z	stdout	No results found for query Brandon Sanderson The Way of Kings 1076
2023-06-25T21:29:30.992771903Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0876
2023-06-25T21:29:30.992704875Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0776
2023-06-25T21:29:30.851768644Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0976
2023-06-25T21:29:30.670986972Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0576
2023-06-25T21:29:30.667695053Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0676
2023-06-25T21:29:30.624784472Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0476
2023-06-25T21:29:30.291508114Z	stdout	No results found for query Stormlight Archives 1 pw spit
2023-06-25T21:29:30.289328901Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0276
2023-06-25T21:29:30.283589143Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0176
2023-06-25T21:29:30.193381250Z	stdout	No results found for query Stormlight Archive 01 The Way of Kings
2023-06-25T21:29:30.020378110Z	stdout	No results found for query 4jPMW73Zuvk7N6sj
2023-06-25T21:29:30.019887750Z	stdout	No results found for query Brandon Sanderson The Way of Kings 0376
2023-06-25T09:59:29.972008340Z	stdout	[2023-06-25 09:59:28,826: INFO/MainProcess] celery@Bragibooks ready.
2023-06-25T09:59:28.797013401Z	stdout	[2023-06-25 09:59:28,796: INFO/MainProcess] Connected to sqla+sqlite:////config/db.sqlite3
2023-06-25T09:59:28.703087773Z	stdout	[0m
2023-06-25T09:59:28.703059864Z	stdout	  . importer.tasks.m4b_merge_task
2023-06-25T09:59:28.703034841Z	stdout	[tasks]
2023-06-25T09:59:28.703008182Z	stdout	[0m[0m
2023-06-25T09:59:28.702983426Z	stdout	                
2023-06-25T09:59:28.702951229Z	stdout	                .> celery           exchange=celery(direct) key=celery
2023-06-25T09:59:28.702921966Z	stdout	 -------------- [queues]
2023-06-25T09:59:28.702879126Z	stdout	--- ***** ----- 
2023-06-25T09:59:28.702849307Z	stdout	-- ******* ---- .> task events: ON
2023-06-25T09:59:28.702817383Z	stdout	- *** --- * --- .> concurrency: 1 (prefork)
2023-06-25T09:59:28.702785651Z	stdout	- ** ---------- .> results:     disabled://
2023-06-25T09:59:28.702750149Z	stdout	- ** ---------- .> transport:   sqla+sqlite:////config/db.sqlite3
2023-06-25T09:59:28.702715711Z	stdout	- ** ---------- .> app:         bragibooks_proj:0x7f3735fcd010
2023-06-25T09:59:28.702685679Z	stdout	- ** ---------- [config]
2023-06-25T09:59:28.702660297Z	stdout	- *** --- * --- 
2023-06-25T09:59:28.702620134Z	stdout	-- ******* ---- Linux-4.4.180+-x86_64-with 2023-06-25 09:59:28
2023-06-25T09:59:28.702591908Z	stdout	--- ***** ----- 
2023-06-25T09:59:28.702493404Z	stdout	 -------------- celery@Bragibooks v5.2.7 (dawn-chorus)
2023-06-25T09:59:28.466581230Z	stdout	[1;36m 
2023-06-25T09:59:24.538618687Z	stdout	[2023-06-25 09:59:24 +0000] [28] [INFO] Booting worker with pid: 28
2023-06-25T09:59:24.501948515Z	stdout	[2023-06-25 09:59:24 +0000] [27] [INFO] Booting worker with pid: 27
2023-06-25T09:59:24.497407679Z	stdout	[2023-06-25 09:59:24 +0000] [16] [INFO] Using worker: gthread
2023-06-25T09:59:24.497341605Z	stdout	[2023-06-25 09:59:24 +0000] [16] [INFO] Listening at: http://0.0.0.0:8000 (16)
2023-06-25T09:59:24.496548137Z	stdout	[2023-06-25 09:59:24 +0000] [16] [INFO] Starting gunicorn 20.1.0
2023-06-25T09:59:23.551275518Z	stdout	128 static files copied to '/home/app/web/static'.
2023-06-25T09:59:23.017870970Z	stdout	
2023-06-25T09:59:22.036085775Z	stdout	  No migrations to apply.
2023-06-25T09:59:21.287516059Z	stdout	[36;1mRunning migrations:[0m
2023-06-25T09:59:21.287402376Z	stdout	[1m  Apply all migrations: [0madmin, auth, contenttypes, importer, sessions
2023-06-25T09:59:20.726552350Z	stdout	[36;1mOperations to perform:[0m
2023-06-25T09:59:11.828646474Z	stdout	Starting with UID: 99, GID: 100
2023-06-25T09:59:11.828574812Z	stdout	chown: unknown user/group appuser:appuser
2023-06-25T09:59:11.828224256Z	stdout	adduser: unknown group appgroup
2023-06-25T09:59:11.826927144Z	stdout	addgroup: gid '100' in use
