### ISSUE TITLE
Server error on attempt to login

### ISSUE THREAD

**Issue by HStep20** [djdembeck/bragibooks#36]
OS: Unraid
Build: Both main and Develop have the issue

Ive got the container built, and the application running, but when I try to log in to Audible I get this error:

```
Internal Server Error: /import/auth
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)
TypeError: post() takes 1 positional argument but 2 were given
```
I don't believe I have OTP enabled on my account, but a bit more direction that the line of terminal access would be helpful for other users determining when and how to utilize the functionality if the need arises.

**Comment by djdembeck** [comment]
Hey there! Thanks for the report :)

While I've fixed the cause of this particular error for now in `develop` (docker image should be done building pretty soon in the packages section), ultimately login via web is very much not where I want it to be. I plan on building the captcha and OTP into the auth page, but hadn't prioritized it till now: https://github.com/djdembeck/bragibooks/issues/11

You can try the fix now and see if it get's everything setup. If it does not, I've also added the ability to login easily from the terminal tool:
- First, get into the container's shell (unraid has a gui option for this by clicking on the running container).
- `m4b-merge --login`

**Comment by HStep20** [comment]
Now it's got another error:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
return handler(request, *args, **kwargs)
File "/home/app/webapp/importer/views.py", line 33, in post
aud_reg.register()
File "/usr/local/lib/python3.8/site-packages/m4b_merge/audible_helper.py", line 37, in register
auth = audible.Authenticator.from_login(
File "/usr/local/lib/python3.8/site-packages/audible/auth.py", line 357, in from_login
auth.re_login(
File "/usr/local/lib/python3.8/site-packages/audible/auth.py", line 583, in re_login
login_device = login(
File "/usr/local/lib/python3.8/site-packages/audible/login.py", line 318, in login
guess = default_captcha_callback(captcha_url)
File "/usr/local/lib/python3.8/site-packages/audible/login.py", line 36, in default_captcha_callback
guess = input("Answer for CAPTCHA: ")
EOFError: EOF when reading a line
display-im6.q16: unable to open X server `' @ error/display.c/DisplayImageCommand/433.
```

As for logging in through the terminal, Ive tried a variety of options, and none go through. Most come back with 'error: unrecognized arguments: --login'

Ive tried various adaptations of it:
* m4b-merge --login : 'error: the following arguments are required: -i/--inputs'
* m4b-merge --login --inputs "email" "pwd" : 'error: unrecognized arguments: --login'
* m4b-merge -i "email" -i "pwd" --login : m4b-merge: error: argument -i/--inputs: expected at least one argument
etc.

**Comment by djdembeck** [comment]
It looks like you didn't get the `m4b-merge` update. Run this and then try `m4b-merge --login` again:
`pip install --no-cache-dir --force https://codeload.github.com/djdembeck/m4b-merge/zip/refs/heads/main`

**Comment by HStep20** [comment]
I ran the command, and it pulled, built, and downloaded all of the packages related, and then it still refused to work. Getting a similar problem with asking for inputs when I only run 'm4b-merge', and telling me '--login unrecognized' when I run 'm4b-merge' with -i parameters.

I did run the command from the root directory of the container, so I tried to 'find . | grep m4b', and it didn't return any results in the container.

**Comment by djdembeck** [comment]
I'm so sorry, I meant for the command to use `develop`, not `main`. I edited the above command now if you can please try it again :)

**Comment by HStep20** [comment]
Ah, that did it - Now its morphed into a captcha problem :P

`Answer for CAPTCHA: display-im6.q16: unable to open X server `' @ error/display.c/DisplayImageCommand/433.`

**Comment by djdembeck** [comment]
That's now the issue I need to add a feature for (which I will when I get some time).

In the meantime, you can try installing m4b-merge on your local PC and running `m4b-merge --login`. Then you can copy `.aud_auth.txt` to your docker config folder for Bragi Books.

`.aud_auth.txt` will be stored in:
>   Mac OS X:               ~/Library/Preferences/<AppName>
>   Unix:                   ~/.config/<AppName>     # or in $XDG_CONFIG_HOME, if defined
>   Win:   C:\Users\<username>\AppData\Local\<AppAuthor>\<AppName>
Though, I've never explicitly run `m4b-merge` on other platforms besides Linux

**Comment by djdembeck** [comment]
Just an update on this, I have an OTP method written for the browser, and am working on Captcha over the weekend

**Comment by djdembeck** [comment]
Hey @HStep20, when you get the chance, can you try the latest `develop` image? I couldn't find a satisfactory fix for full-browser sign in, so I wrote a workaround. Essentially a fixed up `m4b-merge --login`, which addresses your previous issue with not displaying due to the X server not being connected.

Hoping to get you up and running now!

**Comment by HStep20** [comment]
Ran it, Went through the process, approved the email, hit enter, and got this:

```
Traceback (most recent call last):
  File "/usr/local/bin/m4b-merge", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/m4b_merge/__main__.py", line 64, in main
    run_auth = aud.handle_auth()
  File "/usr/local/lib/python3.8/site-packages/m4b_merge/audible_helper.py", line 19, in handle_auth
    self.register()
  File "/usr/local/lib/python3.8/site-packages/m4b_merge/audible_helper.py", line 40, in register
    auth = audible.Authenticator.from_login(
  File "/usr/local/lib/python3.8/site-packages/audible/auth.py", line 357, in from_login
    auth.re_login(
  File "/usr/local/lib/python3.8/site-packages/audible/auth.py", line 583, in re_login
    login_device = login(
  File "/usr/local/lib/python3.8/site-packages/audible/login.py", line 387, in login
    url = login_soup.find_all("a", class_="a-link-normal")[1]["href"]
IndexError: list index out of range
```

**Comment by djdembeck** [comment]
I am happy to say that this PR, https://github.com/djdembeck/bragibooks/pull/45, will remove the need to login into audible :) This issue will be closed upon it being merged to main.
