### ISSUE TITLE
Server Error (500) after submitting ASIN

### ISSUE THREAD

**Issue by seannymurrs** [djdembeck/bragibooks#58]
```
Internal Server Error: /import/match

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view

    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch

    return handler(request, *args, **kwargs)

  File "/home/app/web/importer/views.py", line 104, in post

    helpers.validate_asin(asin)

  File "/usr/local/lib/python3.9/site-packages/m4b_merge/helpers.py", line 88, in validate_asin

    check = requests.get(f"{config.api_url}/{asin}")

AttributeError: module 'm4b_merge.config' has no attribute 'api_url'
```

**Comment by seannymurrs** [comment]
I just tried reverting back to the "main" branch vs the "develop" Docker branch, and I no longer receive the error.

**Comment by djdembeck** [comment]
Yes, the develop branch is using a new version of m4b merge that I still need to do some tinkering with. Thanks for letting me know!
