### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by rubylaser** [djdembeck/bragibooks#61]
I'm sure that this is user error, but I had been using Bragibooks successfully until my last two imports.  Now, when I type in the ASIN (#1250814936) and Submit it, it returns a Server 500 error.  I saw this other [closed ticket](https://github.com/djdembeck/bragibooks/issues/58), but I'm already running the main branch.

This is the message in the log file.  I tried turning the log level up to INFO, but I didn't get anything more verbose than I was get at WARNING.

```
Operations to perform:,
  Apply all migrations: auth, contenttypes, importer, sessions,
Running migrations:,
  No migrations to apply.,
[2021-12-03 14:40:03 +0000] [11] [INFO] Starting gunicorn 20.1.0,
[2021-12-03 14:40:03 +0000] [11] [INFO] Listening at: http://0.0.0.0:8000 (11),
[2021-12-03 14:40:03 +0000] [11] [INFO] Using worker: gthread,
[2021-12-03 14:40:03 +0000] [12] [INFO] Booting worker with pid: 12,
[2021-12-03 14:40:03 +0000] [13] [INFO] Booting worker with pid: 13,
Internal Server Error: /import/match,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner,
    response = get_response(request),
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response,
    response = wrapped_callback(request, *callback_args, **callback_kwargs),
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view,
    return self.dispatch(request, *args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch,
    return handler(request, *args, **kwargs),
  File "/home/app/web/importer/views.py", line 105, in post,
    helpers.validate_asin(existing_settings.api_url, asin),
AttributeError: 'NoneType' object has no attribute 'api_url'
```

This is running in Docker with the following docker-compose.yml

```
version: '3.3'
services:
    bragibooks:
        container_name: bragibooks
        environment:
          - PUID=1000
          - PGID=1000
          - LOG_LEVEL=INFO
        volumes:
          - /docker/containers/bragibooks/config:/config
          - /docker/downloads/completed/Audiobooks:/input
          - /storage/audiobooks:/output
        ports:
          - 8001:8000
        restart: unless-stopped
        image: ghcr.io/djdembeck/bragibooks:main
```

Any advice it greatly appreciated!

**Comment by djdembeck** [comment]
Try going to the settings page and clicking save.

This looks to be an initialization issue.

**Comment by rubylaser** [comment]
I feel like an idiot for not trying that.  After saving the settings, it's back working great. Thanks for the help and the great software!
