### ISSUE TITLE
Timeout error | folder config?

### ISSUE THREAD

**Issue by jcrmit** [djdembeck/bragibooks#66]
Hi - great app @djdembeck 

I have setup using Docker ghcr.io/djdembeck/bragibooks:main
Within the docker I have set up the input and output folders - as per instructions. 

Assume input = location of audiobooks to be merged - on the import page
Assume output = location of final merged, tagged, m4b

What is the 'Directory for copy of original input files' on the settings page?

When I ran a merge - 
- I can select a folder with multiple mp3s (2)
- I can add the ASIN and click submit

This is the following log file output: -
`0 remaining /    2 total, preparing next task \
could not convert /input/Siege and Storm/Siege and Storm Part 1.mp3 to /mnt/downloads/media/books/output/Leigh Bardugo/Siege and Storm/Siege and Storm-tmpfiles/1-finished.m4b
Input path vs junk dir:
/input/Siege and Storm
/mnt/downloads/rutorrent/readarr
Couldn't find junk dir relative to input
Using existing chapter data
Internal Server Error: /import/match
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/app/web/importer/views.py", line 138, in post
    merge_object.run_m4b_merge()
  File "/home/app/web/utils/merge.py", line 37, in run_m4b_merge
    self.m4b.run_merge()
  File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 251, in run_merge
    self.merge_multiple_files()
  File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 304, in merge_multiple_files
    self.fix_chapters()
  File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 424, in fix_chapters
    with open(chapter_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/downloads/media/books/output/Leigh Bardugo/Siege and Storm/Siege and Storm.chapters.txt'`

Not sure if it is something to do with folder configurations? `Input path vs junk dir:` `Couldn't find junk dir relative to input`

Could you help me troubleshoot my implementation?

**Comment by garlik82** [comment]
Hi there. I had this issue once, If I remember correctly it was related with folder permissions. hope this helps.

**Comment by djdembeck** [comment]
That field could be clearer for sure. Here is an example of what mine is:

![screenshot-10 0 105 16_8000-2022 01 09-14_36_43](https://user-images.githubusercontent.com/71412966/148699840-062be5e5-f5e7-4c65-b559-431e3979a866.png)

**Comment by jcrmit** [comment]
@garlik82 - thanks - folder permissions was the first thought and I did make sure it was set up correctly.
@djdembeck - thanks for the example of your set-up - is helpful. It wasn't clear (though makes sense) to use the contain mounts not the full paths - which I was. Spinning is up now and will let you know how it goes.
